### ISSUE TITLE
Which json value tells me whether the battle was victory or defeat?

### ISSUE THREAD

**Issue by Jondeboy** [gabriel-oana/wotreplay#4]

**Comment by gabriel-oana** [comment]
The way to determine the winning team is as follows:

1. In the "common" response there is a parameter called "winner_team". 
2. In the "battle_performance" response there is a parameter called "team". 

So if "team" = 1 and "winner_team" = 2 then the battle was lost. 
If "team" = 1 and "winner_team" = 1 then the battle was won.

**Comment by Jondeboy** [comment]
Thanks alot for quick response!
