### ISSUE TITLE
Invalid JSON syntax in "replay_date"

### ISSUE THREAD

**Issue by Jondeboy** [gabriel-oana/wotreplay#5]
When I use this library to get JSON data, the "replay_date" syntax is wrong. Please check the following example json using [online JSON validator](https://jsonlint.com/): 

[{
	'replay_date': datetime.datetime(2022, 11, 19, 19, 57, 4),
	'file_id': 0,
	'player_vehicle': 'france-F25_Lorraine155_51',
	'nation': 'france'
}]

**Comment by gabriel-oana** [comment]
The output is not supposed to be in JSON format (string) but instead as a python list of dictionaries. 
The general standard is to output objects that can be further parsed by the end user. 

If you need this as JSON, it's up to you to change the values from python objects (datetime) to strings then convert to JSON file.

**Comment by gabriel-oana** [comment]
That however, is something that could be as an option to be selected by the user. 
I'll have a think about it and check how difficult would be to implement that.

**Comment by Jondeboy** [comment]
I understand. Im new in python so I didnt realize they were list of dictionaries. Thanks for your answer.
